/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asbamboo.java.sdk;

import org.junit.Test;
import static org.junit.Assert.*;

public class AsbambooTest {
    @Test public void testSomeLibraryMethod() {
    	Asbamboo classUnderTest = new Asbamboo();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
